### ISSUE TITLE
Unexpected token new

### ISSUE THREAD

**Issue by omerkocaaga** [jantimon/favicons-webpack-plugin#129]
webpack.prod.conf.js

```
let FaviconsWebpackPlugin = require('favicons-webpack-plugin')
...
plugins: [
...
    new FaviconsWebpackPlugin('./src/assets/favicon/icon.png')
]
```

And I get this error when I am `npm run build`

```
/Users/omer/Sites/refactor/build/webpack.prod.conf.js:126
    new FaviconsWebpackPlugin('./src/assets/favicon/icon.png')
    ^^^

SyntaxError: Unexpected token new
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! refactor@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the refactor@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/omer/.npm/_logs/2018-05-31T19_12_57_497Z-debug.log
```

**Comment by jantimon** [comment]
You have to require it first
