### ISSUE TITLE
Does not work at all with webpack 4

### ISSUE THREAD

**Issue by pmnc** [jantimon/favicons-webpack-plugin#148]
Webpack 4 has great improvements over webpack 3, everything becomes more clearly expressed, better stated.
The only solution I got is run a build with webpack 3 to get favicons and commit them to our repo. Not elegant at all ...

wouldn't it be nice to have a 1.0.x release compatible with webpack 4 ?
Thanks in advance

**Comment by nstuyvesant** [comment]
Just started using favicons-webpack-plugin this morning. Seems to work ok for me using webpack 4.29.5.

The relevant part of my webpack configuration...
```javascript
import FaviconsWebpackPlugin from 'favicons-webpack-plugin';

  if(production) {
    config.plugins.push(
      new FaviconsWebpackPlugin({
        logo: './client/assets/images/seal.svg',
        inject: true,
        title: 'Schoolhouse Yoga',
        icons: {
          android: true,
          appleIcon: true,
          appleStartup: true,
          favicons: true,
          firefox: true,
          opengraph: true,
          twitter: true,
          yandex: false,
          windows: true
        }
      })
    );
  }

```

I'm also using HtmlWebpackPlugin which is required for favicons-webpack-plugin.

**Comment by pmnc** [comment]
Thanks for your answer, it's hard to tell what's going wrong.

I am not using HtmlWebpackPlugin  and my conf is:
`    new FaviconsWebpackPlugin({
      logo: './assets/images/favicon/favicon.png',
      prefix: '../images/icons/[name]-[hash]-',
      emitStats: true,
      statsFilename: '../conf/icons-manifest.json',
      title: 'Rakuten',
      persistentCache: true,
      icons: {
        android: true,
        appleIcon: true,
        appleStartup: true,
        coast: false,
        favicons: true,
        firefox: false,
        opengraph: false,
        twitter: false,
        yandex: false,
        windows: false,
      },
    }),
`
and I got that :

`  build [==                  ] 10% (0.0 seconds)TypeError: Cannot read property 'tapAsync' of undefined
    at /home/philippe/proj/canopy_vis_fo/node_modules/favicons-webpack-plugin/index.js:73:62
    at SyncHook.eval [as call] (eval at create (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:111:1)
    at SyncHook.lazyCompileHook (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/Compiler.js:581:26)
    at hooks.beforeCompile.callAsync.err (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/Compiler.js:617:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/Compiler.js:612:28)
    at Compiler.runAsChild (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/Compiler.js:291:8)
    at /home/philippe/proj/canopy_vis_fo/node_modules/favicons-webpack-plugin/lib/compiler.js:75:19
    at new Promise (<anonymous>)
    at Object.compileTemplate (/home/philippe/proj/canopy_vis_fo/node_modules/favicons-webpack-plugin/lib/compiler.js:74:10)
    at /home/philippe/proj/canopy_vis_fo/node_modules/favicons-webpack-plugin/index.js:48:19
    at AsyncParallelHook.eval [as callAsync] (eval at create (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:13:1)
    at AsyncParallelHook.lazyCompileHook (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeCompile.callAsync.err (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/Compiler.js:619:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/Compiler.js:612:28)
    at readRecords.err (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/Compiler.js:284:11)
    at Compiler.readRecords (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/Compiler.js:479:11)
    at hooks.run.callAsync.err (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/Compiler.js:281:10)
    at _err0 (eval at create (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:20:1)
    at compiler.hooks.run.tapAsync (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/CachePlugin.js:52:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/Compiler.js:278:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/philippe/proj/canopy_vis_fo/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.run (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/Compiler.js:275:24)
    at runWithDependencies (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/MultiCompiler.js:258:15)
    at asyncLib.map (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/MultiCompiler.js:178:6)
    at arrayEachIndex (/home/philippe/proj/canopy_vis_fo/node_modules/neo-async/async.js:2543:9)
    at Object.map (/home/philippe/proj/canopy_vis_fo/node_modules/neo-async/async.js:2897:9)
    at runCompilers (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/MultiCompiler.js:175:13)
    at MultiCompiler.runWithDependencies (/home/philippe/proj/canopy_vis_fo/node_modules/webpack/lib/MultiCompiler.js:187:3)
`

**Comment by michidk** [comment]
Getting the same error, using v4.25.1

**Comment by jantimon** [comment]
Done in #157.

Can you please take a look?
