### ISSUE TITLE
Not compatible with speed-measure-webpack-plugin: ^1.3.0

### ISSUE THREAD

**Issue by fengyun2** [jantimon/favicons-webpack-plugin#151]
### version: 
- webpack:  4.29.3
- speed-measure-webpack-plugin:  1.3.0
- favicons-webpack-plugin: 0.0.9

### platform

- windows10
- node: v10.3.0

```js
const FaviconsWebpackPlugin = require('favicons-webpack-plugin');
const SpeedMeasurePlugin = require('speed-measure-webpack-plugin');

const smp = new SpeedMeasurePlugin();
const webpackConfig = smp.wrap({
plugins: [
 new FaviconsWebpackPlugin({
   logo: path.join(basePath, 'public/favicon.png'),
   prefix: 'icons/',
   // Generate a cache file with control hashes and
   // don't rebuild the favicons until those hashes change
   persistentCache: false,
   // Inject the html into the html-webpack-plugin
   inject: true,
   icons: {
     appleIcon: true, 
     android: false,
     firefox: false,
     appleStartup: false
   }
 }),
]
});
```

### error:

```bash
\node_modules\favicons-webpack-plugin\index.js:73
            cmpp.hooks.htmlWebpackPluginBeforeHtmlProcessing.tapAsync(
                                                             ^

TypeError: Cannot read property 'tapAsync' of undefined
    at Proxy.<anonymous> (D:\test\js\20190214\webpack4-demo\node_modules\favicons-webpack-plugin\index.js:73:62)
    at args (D:\test\js\20190214\webpack4-demo\node_modules\speed-measure-webpack-plugin\WrappedPlugin\index.js:52:19)
    at SyncHook.eval [as call] (eval at create (D:\test\js\20190214\webpack4-demo\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:113:1)
    at SyncHook.lazyCompileHook (D:\test\js\20190214\webpack4-demo\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (D:\test\js\20190214\webpack4-demo\node_modules\webpack\lib\Compiler.js:581:26)
    at hooks.beforeCompile.callAsync.err (D:\test\js\20190214\webpack4-demo\node_modules\webpack\lib\Compiler.js:617:29)
    at _err1 (eval at create (D:\test\js\20190214\webpack4-demo\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:16:1)
    at func.apply.argsButLast.map.concat.callbackArgs (D:\test\js\20190214\webpack4-demo\node_modules\speed-measure-webpack-plugin\WrappedPlugin\index.js:44:9)
    at compiler.inputFileSystem.readFile (D:\test\js\20190214\webpack4-demo\node_modules\webpack\lib\DllReferencePlugin.js:72:15)
    at process.nextTick (D:\test\js\20190214\webpack4-demo\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:73:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error Command failed with exit code 1.
```

**Comment by jantimon** [comment]
This is probably a bug of the spped-measure-webpack-plugin which hooks into the favicons-webpack-plugin.

The speed measurement plugin can not measure async parallelism as it only measures the start and the beginning of a hook.

Maybe my cpuprofile-webpack-plugin can help you here as it measures the real cpu usage by every plugin and loader: https://github.com/jantimon/cpuprofile-webpack-plugin
