### ISSUE TITLE
Favicons compilation is causing postcss to erroneously report a css error

### ISSUE THREAD

**Issue by leiyangyou** [jantimon/favicons-webpack-plugin#153]
Hi, the compilation of favicon seems to cause postcss to erroneously report a css error

```
ERROR in ./index.css
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: _this.setMessage is not a function
    at new CssSyntaxError (/Users/leiyang/Workspace/opensource/postcss-error-bug/node_modules/postcss/lib/css-syntax-error.js:162:11)
    at Input.error (/Users/leiyang/Workspace/opensource/postcss-error-bug/node_modules/postcss/lib/input.js:130:16)
    at Parser.unknownWord (/Users/leiyang/Workspace/opensource/postcss-error-bug/node_modules/postcss/lib/parser.js:563:22)
    at Parser.decl (/Users/leiyang/Workspace/opensource/postcss-error-bug/node_modules/postcss/lib/parser.js:235:16)
    at Parser.other (/Users/leiyang/Workspace/opensource/postcss-error-bug/node_modules/postcss/lib/parser.js:133:18)
    at Parser.parse (/Users/leiyang/Workspace/opensource/postcss-error-bug/node_modules/postcss/lib/parser.js:77:16)
    at parse (/Users/leiyang/Workspace/opensource/postcss-error-bug/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/Users/leiyang/Workspace/opensource/postcss-error-bug/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/Users/leiyang/Workspace/opensource/postcss-error-bug/node_modules/postcss/lib/processor.js:138:12)
    at Processor.process (/Users/leiyang/Workspace/opensource/postcss-error-bug/node_modules/postcss/lib/processor.js:117:23)
    at Promise.resolve.then.then (/Users/leiyang/Workspace/opensource/postcss-error-bug/node_modules/postcss-loader/src/index.js:141:8)
```

it's reproduced here

https://github.com/leiyangyou/postcss-error-reproduction.git

**Comment by leiyangyou** [comment]
this is due to usage of an old version of favicons (which uses harmony-reflect that's causing the problem)

**Comment by mikehoren** [comment]
Is there plans to upgrade the favicons dependency to a version greater than 5.1 to remedy this issue?  I'm encountering the same error as I'm upgrading my tooling.

**Comment by ssilve1989** [comment]
Any update on this?

**Comment by jantimon** [comment]
Done in #157.

Can you please take a look?
