### ISSUE TITLE
Path variable [hash] is not implemented in light mode

### ISSUE THREAD

**Issue by andy128k** [jantimon/favicons-webpack-plugin#159]
In light mode hash is undefined and plugin doesn't work.

**Comment by jantimon** [comment]
Thanks @andy128k I'll take a look

**Comment by andy128k** [comment]
[Configuration](https://github.com/andy128k/password-storage-web/blob/master/webpack.config.js#L49-L67)

[Webpack is 4.39.2](https://github.com/andy128k/password-storage-web/blob/master/yarn.lock#L8279)

Related error is

```
Error: Path variable [hash] not implemented in this context: icons-[hash]/
    at fn (/Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/TemplatedPathPlugin.js:44:11)
    at fn (/Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/TemplatedPathPlugin.js:32:16)
    at String.replace (<anonymous>)
    at replacePathVariables (/Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/TemplatedPathPlugin.js:98:5)
    at SyncWaterfallHook.eval [as call] (eval at create (/Users/andy/projects/private/password-storage-web/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncWaterfallHook.lazyCompileHook (/Users/andy/projects/private/password-storage-web/node_modules/tapable/lib/Hook.js:154:20)
    at MainTemplate.getAssetPath (/Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/MainTemplate.js:521:31)
    at module.exports.getAssetPath (/Users/andy/projects/private/password-storage-web/node_modules/favicons-webpack-plugin/src/compat.js:6:20)
    at /Users/andy/projects/private/password-storage-web/node_modules/favicons-webpack-plugin/src/index.js:108:46
    at new Promise (<anonymous>)
    at FaviconsWebpackPlugin.generateFaviconsLight (/Users/andy/projects/private/password-storage-web/node_modules/favicons-webpack-plugin/src/index.js:105:12)
    at /Users/andy/projects/private/password-storage-web/node_modules/favicons-webpack-plugin/src/index.js:65:37
    at AsyncParallelHook.eval [as callAsync] (eval at create (/Users/andy/projects/private/password-storage-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at AsyncParallelHook.lazyCompileHook (/Users/andy/projects/private/password-storage-web/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/Compiler.js:659:20
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/andy/projects/private/password-storage-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/andy/projects/private/password-storage-web/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/Compiler.js:652:28)
    at /Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/Compiler.js:519:11)
    at /Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/Compiler.js:318:10
    at eval (eval at create (/Users/andy/projects/private/password-storage-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/CachePlugin.js:52:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/andy/projects/private/password-storage-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/andy/projects/private/password-storage-web/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/Compiler.js:315:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/andy/projects/private/password-storage-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/andy/projects/private/password-storage-web/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.run (/Users/andy/projects/private/password-storage-web/node_modules/webpack/lib/Compiler.js:312:24)
    at processOptions (/Users/andy/projects/private/password-storage-web/node_modules/webpack-cli/bin/cli.js:352:14)
```

**Comment by jantimon** [comment]
Thanks 👍

**Comment by jantimon** [comment]
Released a fix in 1.0.1 can you please test if it works for you?

**Comment by andy128k** [comment]
@jantimon Thanks! Now it works well!

One more thing. Default length of hash in light mode is different (two times larger) from webapp mode. But this is not a problem at all.

**Comment by jantimon** [comment]
Cool thanks for your update 👍
