### ISSUE TITLE
Overwritting favicons config

### ISSUE THREAD

**Issue by whoisjorge** [jantimon/favicons-webpack-plugin#183]
Hi! Is it posible to overwrite `favicons` **config folder** in any way with the current code? I would like more flexibility when choosing what to generate to fit the `@vue/cli-plugin-pwa` needs.

https://github.com/itgalaxy/favicons/tree/master/src/config

**Comment by jantimon** [comment]
You can merge configs and send them directly to the plugin using the `options` property

**Comment by whoisjorge** [comment]
@jantimon thanks for the quick response! I would like to do something like that to choose exactly which icons should be generated by the plugin, but it throws me an error 

```js
favicons: {
  icons: {
    android: {
      "android-chrome-192x192.png": {
        "width": 192,
        "height": 192,
        "transparent": true,
        "rotate": false,
        "mask": false
      },
      "android-chrome-512x512.png": {
        "width": 512,
        "height": 512,
        "transparent": true,
        "rotate": false,
        "mask": false
      }
    }
  }
}
```

**Comment by jantimon** [comment]
Which error do you get?

**Comment by whoisjorge** [comment]
> Which error do you get?
> Does it still happen with 2.1.0 ?

Yes, I am using 2.1.0

```node
Building for production...(node:789) UnhandledPromiseRejectionWarning: Error: Unsupported option 'android-chrome-192x192.png' on platform 'android'
    at Object.preparePlatformOptions (.../node_modules/favicons/dist/helpers.js:156:19)
    at createFavicons (.../node_modules/favicons/dist/index.js:69:39)
    at createPlatform (.../node_modules/favicons/dist/index.js:74:25)
    at create (.../node_modules/favicons/dist/index.js:86:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:789) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:789) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 ERROR  Error: Unsupported option 'android-chrome-192x192.png' on platform 'android'
Error: Unsupported option 'android-chrome-192x192.png' on platform 'android'
    at Object.preparePlatformOptions (.../node_modules/favicons/dist/helpers.js:156:19)
    at createFavicons (.../node_modules/favicons/dist/index.js:69:39)
    at createPlatform (.../node_modules/favicons/dist/index.js:74:25)
    at create (.../node_modules/favicons/dist/index.js:86:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
```

**Comment by jantimon** [comment]
You can use only the options listed in the readme: https://github.com/itgalaxy/favicons

The options `android-chrome-192x192.png` seems to be wrong
