### ISSUE TITLE
Error: w and h must be numbers

### ISSUE THREAD

**Issue by CapitalCloud** [jantimon/favicons-webpack-plugin#24]
at Jimp.throwError (/srv/filestore/service/ccloud_front/20160821154947/node_modules/jimp/index.js:82:43)
    at Jimp.contain (/srv/filestore/service/ccloud_front/20160821154947/node_modules/jimp/index.js:1751:27)
    at Object.resize (/srv/filestore/service/ccloud_front/20160821154947/node_modules/favicons/helpers-es5.js:221:27)
    at /srv/filestore/service/ccloud_front/20160821154947/node_modules/favicons/es5.js:60:41
    at fn (/srv/filestore/service/ccloud_front/20160821154947/node_modules/async/lib/async.js:746:34)
    at /srv/filestore/service/ccloud_front/20160821154947/node_modules/async/lib/async.js:1213:16
    at /srv/filestore/service/ccloud_front/20160821154947/node_modules/async/lib/async.js:166:37
    at /srv/filestore/service/ccloud_front/20160821154947/node_modules/async/lib/async.js:706:43
    at /srv/filestore/service/ccloud_front/20160821154947/node_modules/async/lib/async.js:167:37
    at Jimp.<anonymous> (/srv/filestore/service/ccloud_front/20160821154947/node_modules/async/lib/async.js:1209:30)
    at /srv/filestore/service/ccloud_front/20160821154947/node_modules/jimp/index.js:289:27
    at null.<anonymous> (/srv/filestore/service/ccloud_front/20160821154947/node_modules/pngjs/lib/png.js:74:7)
    at g (events.js:273:16)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at null.<anonymous> (/srv/filestore/service/ccloud_front/20160821154947/node_modules/pngjs/lib/png.js:36:10)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at ParserAsync._complete (/srv/filestore/service/ccloud_front/20160821154947/node_modules/pngjs/lib/parser-async.js:109:8)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at _filter.Filter.complete (/srv/filestore/service/ccloud_front/20160821154947/node_modules/pngjs/lib/filter-parse-async.js:19:12)
    at Filter._reverseFilterLine (/srv/filestore/service/ccloud_front/20160821154947/node_modules/pngjs/lib/filter-parse.js:169:10)
    at ChunkStream._processRead (/srv/filestore/service/ccloud_front/20160821154947/node_modules/pngjs/lib/chunkstream.js:174:13)
    at ChunkStream._process (/srv/filestore/service/ccloud_front/20160821154947/node_modules/pngjs/lib/chunkstream.js:193:14)
    at ChunkStream.write (/srv/filestore/service/ccloud_front/20160821154947/node_modules/pngjs/lib/chunkstream.js:61:8)
    at Inflate.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Inflate.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! ccloud@0.0.0 build: `webpack --config webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccloud@0.0.0 build script 'webpack --config webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ccloud package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ccloud
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ccloud
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/filestore/service/ccloud_front/20160821154947/npm-debug.log

and i edit the file node_modules/favicons-webpack-plugin/lib/loader.js 

var favicons = require('favicons/es5'); to var favicons = require('favicons');

this error is gone!

**Comment by jantimon** [comment]
Please report those bugs to the favicons project

**Comment by CapitalCloud** [comment]
and i edit the file node_modules/favicons-webpack-plugin/lib/loader.js

var favicons = require('favicons/es5'); to var favicons = require('favicons');

this error is gone!

**Comment by jantimon** [comment]
nice find 👍
but still the issue is the broken es5 version of `favicons`.
