### ISSUE TITLE
v5.0.0-alpha.4 is missing a module

### ISSUE THREAD

**Issue by cmloegcmluin** [jantimon/favicons-webpack-plugin#243]
Been getting this since yesterday. Indeed that module seems to be missing. Let me know if you need any other info besides this error output:

```sh
> webpack

[webpack-cli] Failed to load '~\webpack.config.js'
[webpack-cli] Error: Cannot find module 'favicons'
Require stack:
- ~\node_modules\favicons-webpack-plugin\src\index.js
- ~\webpack.config.js
- ~\node_modules\webpack-cli\lib\webpack-cli.js
- ~\node_modules\webpack-cli\lib\bootstrap.js
- ~\node_modules\webpack-cli\bin\cli.js
- ~\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (~\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (~\node_modules\favicons-webpack-plugin\src\index.js:6:18)
    at Module._compile (~\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '$HOME\\node_modules\\favicons-webpack-plugin\\src\\index.js',
    '$HOME\\webpack.config.js',
    '$HOME\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    '$HOME\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    '$HOME\\node_modules\\webpack-cli\\bin\\cli.js',
    '$HOME\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! sagittal-app@1.0.131 build: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the sagittal-app@1.0.131 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DouglasBlumeyer\AppData\Roaming\npm-cache\_logs\2021-01-07T18_29_28_460Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! sagittal-app@1.0.130 deploy: `sh bin/deploy.sh`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the sagittal-app@1.0.130 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~\AppData\Roaming\npm-cache\_logs\2021-01-07T18_29_28_502Z-debug.log
```

**Comment by hadimostafapour** [comment]
See [Migrate to Webpack 5](https://github.com/jantimon/favicons-webpack-plugin/projects/1)

"favicons" is now a peer dependency, install it by `npm i favicons`.

**Comment by jantimon** [comment]
In the past we had some issues with users requesting her different favicon version so we made it a peer dependency as @hadimostafapour said

**Comment by jantimon** [comment]
I added a better error message for v5.0.0-alpha.5
