### ISSUE TITLE
Errors in webpack with version 5.0.0-alpha.8

### ISSUE THREAD

**Issue by 97carmine** [jantimon/favicons-webpack-plugin#245]
With the version 5.0.0-alpha.8 with webpack 5.17.0

```
[...]

(node:2536) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createSnapshot' of undefined
    at D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:111:36
    at new Promise (<anonymous>)
    at createSnapshot (D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:110:10)
    at runCached (D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:81:23)
    at D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:64:16
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3761)
(node:2536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:2536) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'readFile' of undefined
    at D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:174:41
    at new Promise (<anonymous>)
    at D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:173:11
    at Array.map (<anonymous>)
    at readFiles (D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:170:11)
    at runWithFileCache (D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:151:29)
    at runCached (D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:92:7)
    at D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:64:16
(node:2536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3763)

[...]

[webpack-cli] HookWebpackError: Cannot read property 'readFile' of undefined
    at makeWebpackError (D:\Repositorios\portfolio\.yarn\$$virtual\webpack-virtual-b34ba36b8e\0\cache\webpack-npm-5.17.0-e594321923-2840d6291d.zip\node_modules\webpack\lib\HookWebpackError.js:49:9)
    at D:\Repositorios\portfolio\.yarn\$$virtual\webpack-virtual-b34ba36b8e\0\cache\webpack-npm-5.17.0-e594321923-2840d6291d.zip\node_modules\webpack\lib\Compilation.js:2198:11
    at eval (eval at create (D:\Repositorios\portfolio\.yarn\cache\tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:30:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- inner error --
TypeError: Cannot read property 'readFile' of undefined
    at D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:174:41
    at new Promise (<anonymous>)
    at D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:173:11
    at Array.map (<anonymous>)
    at readFiles (D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:170:11)
    at runWithFileCache (D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:151:29)
    at runCached (D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:92:7)
    at D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:64:16
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read property 'readFile' of undefined
    at D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:174:41
    at new Promise (<anonymous>)
    at D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:173:11
    at Array.map (<anonymous>)
    at readFiles (D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:170:11)
    at runWithFileCache (D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:151:29)
    at runCached (D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:92:7)
    at D:\Repositorios\portfolio\.yarn\$$virtual\favicons-webpack-plugin-virtual-32b93d46b0\0\cache\favicons-webpack-plugin-npm-5.0.0-alpha.8-2305ea6af9-92c1510f65.zip\node_modules\favicons-webpack-plugin\src\cache.js:64:16
```

I have downgraded to the version **5.0.0-alpha.7** and it works properly

**Comment by jantimon** [comment]
Oh thanks for the report - I have no Idea what this stack trace means or causes 🤔 

Can please you provide a reproduction example similar to https://codesandbox.io/s/favicons-webpack-plugin-demo-uh195?file=/webpack.config.js so I can try to investigate the cause?

**Comment by jantimon** [comment]
Can please you try `favicons-webpack-plugin@5.0.0-alpha.10`?

**Comment by 97carmine** [comment]
Great, it works correctly, thanks

**Comment by jantimon** [comment]
Cool thanks for testing 👍
