### ISSUE TITLE
Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by Rawnly** [jantimon/favicons-webpack-plugin#255]
Can't get it running with webpack `4.44.2`

```
[webpack-cli] TypeError: Cannot read property 'tap' of undefined
    at FaviconsWebpackPlugin.apply (/Users/federicovitale/Developer/Chili/chili-website/node_modules/favicons-webpack-plugin/src/index.js:36:31)
    at webpack (/Users/federicovitale/Developer/Chili/chili-website/node_modules/webpack/lib/webpack.js:51:13)
    at WebpackCLI.createCompiler (/Users/federicovitale/Developer/Chili/chili-website/node_modules/webpack-cli/lib/webpack-cli.js:1165:24)
    at async Command.<anonymous> (/Users/federicovitale/Developer/Chili/chili-website/node_modules/@webpack-cli/serve/lib/index.js:65:30)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/Users/federicovitale/Developer/Chili/chili-website/node_modules/webpack-cli/lib/webpack-cli.js:708:13)
error Command failed with exit code 2.
```

**Comment by jantimon** [comment]
Not enough information to reproduce

**Comment by jwanglof** [comment]
Get the same error when running `webpack --config webpack.prod.js` where my `webpack.prod.js` includes the following:

```
const FaviconsWebpackPlugin = require("favicons-webpack-plugin");
{
  plugins: [
    new FaviconsWebpackPlugin()
  ]
}
```

webpack version: 4.46.0
favicons-webpack-plugin version: 5.0.1
favicons version: 6.2.1

Will try to bump webpack to v5 and see if that makes it work.

**Comment by jantimon** [comment]
There is a compatibility section in the readme :)

**Comment by jwanglof** [comment]
> There is a compatibility section in the readme :)

Ah, there it is. Didn't see it before 👍

**Comment by Drifterdnl** [comment]
Same error here. Compatibility section doesn't mention webpack version. Changelog also doesn't mention dropping support for webpack v4. Am I missing something here @jantimon?
