### ISSUE TITLE
[BUG] Doesn't work with webpack@5.23.0

### ISSUE THREAD

**Issue by a2nt** [jantimon/favicons-webpack-plugin#257]
[webpack-cli] HookWebpackError
    at makeWebpackError (/mnt/data/srv/dist/repositories/webpack-bootstrap-ui-kit/node_modules/.pnpm/webpack@5.23.0_webpack-cli@4.5.0/node_modules/webpack/lib/HookWebpackError.js:49:9)
    at /mnt/data/srv/dist/repositories/webpack-bootstrap-ui-kit/node_modules/.pnpm/webpack@5.23.0_webpack-cli@4.5.0/node_modules/webpack/lib/Compilation.js:2382:12
    at eval (eval at create (/mnt/data/srv/dist/repositories/webpack-bootstrap-ui-kit/node_modules/.pnpm/tapable@2.2.0/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:87:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- inner error --
undefined
caused by plugins in Compilation.hooks.processAssets
undefined
error Command failed with exit code 2.

**Comment by jantimon** [comment]
Sorry that's not enough information to reproduce your problem...

Can you please try a minimal reproduction example consisting of a webpack config only with html-webpack-plugin (if used) and favicons-webpack-plugin

And provide me a  a list of used versions (node, webpack, html-webpack-plugin, favicons and favicons-webpack-plugin)

**Comment by a2nt** [comment]
node v12.20.2

favicons-webpack-plugin 5.0.0-alpha.1
html-webpack-plugin 5.2.0
webpack 5.23.0
webpack-cli 4.5.0

**Comment by jantimon** [comment]
Can you please try favicon-webpack-plugin 5.0.1 ?

**Comment by a2nt** [comment]
@jantimon works great, thank you

**Comment by jantimon** [comment]
Cool :)
