### ISSUE TITLE
Error: Could not find the npm peerDependency "favicons".

### ISSUE THREAD

**Issue by thisVioletHydra** [jantimon/favicons-webpack-plugin#283]
## Environment 🖥

```cmd
D:\WWW\frontend-developer-nissan main ≡  ~12 -25 ?4 ❯ yarn build
yarn run v1.22.5
$ webpack --mode=production --node-env=production
[LOG] isProduction <boolean> true
D:\WWW\frontend-developer-nissan\node_modules\favicons-webpack-plugin\src\index.js:562
    throw new Error(
          ^

Error: Could not find the npm peerDependency "favicons".
Please run:
npm i favicons
 - or -
yarn add favicons

Error: Cannot find module 'favicons'
Require stack:
- D:\WWW\frontend-developer-nissan\node_modules\favicons-webpack-plugin\src\index.js
- D:\WWW\frontend-developer-nissan\webpack.config.js
- D:\WWW\frontend-developer-nissan\node_modules\webpack-cli\lib\webpack-cli.js
- D:\WWW\frontend-developer-nissan\node_modules\webpack-cli\lib\bootstrap.js
- D:\WWW\frontend-developer-nissan\node_modules\webpack-cli\bin\cli.js
- D:\WWW\frontend-developer-nissan\node_modules\webpack\bin\webpack.js
    at loadFaviconsLibrary (D:\WWW\frontend-developer-nissan\node_modules\favicons-webpack-plugin\src\index.js:562:11)
    at FaviconsWebpackPlugin.generateFaviconsWebapp (D:\WWW\frontend-developer-nissan\node_modules\favicons-webpack-plugin\src\index.js:403:22)
    at FaviconsWebpackPlugin.generateFavicons (D:\WWW\frontend-developer-nissan\node_modules\favicons-webpack-plugin\src\index.js:315:21)
    at D:\WWW\frontend-developer-nissan\node_modules\favicons-webpack-plugin\src\index.js:117:18
    at D:\WWW\frontend-developer-nissan\node_modules\favicons-webpack-plugin\src\cache.js:155:5
    at CacheFacade.providePromise (D:\WWW\frontend-developer-nissan\node_modules\webpack\lib\CacheFacade.js:337:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

i just run webpack5 in **production** mode ;0

**Comment by ACregan** [comment]
I too am experiencing this. I am running on WSL2 and if I run the same build script on my CI then it installs and runs without issues. Here is my error log:
```

(node:8926) UnhandledPromiseRejectionWarning: Error: Could not find the npm peerDependency "favicons".
Please run:
npm i favicons
 - or -
yarn add favicons

Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/sharp/lib/constructor.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/sharp/lib/index.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons/dist/helpers.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons/dist/index.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js
- /home/c0un7z3r0/DEV/portfolio_new/webpack.config.prod.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/lib/webpack-cli.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/lib/bootstrap.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/bin/cli.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack/bin/webpack.js

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at loadFaviconsLibrary (/home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:562:11)
    at FaviconsWebpackPlugin.generateFaviconsWebapp (/home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:403:22)
    at FaviconsWebpackPlugin.generateFavicons (/home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:315:21)
    at /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:117:18
    at /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/cache.js:155:5
    at CacheFacade.providePromise (/home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack/lib/CacheFacade.js:344:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:8926) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8926) [DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)
[webpack-cli] HookWebpackError: Could not find the npm peerDependency "favicons".
Please run:
npm i favicons
 - or -
yarn add favicons

Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/sharp/lib/constructor.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/sharp/lib/index.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons/dist/helpers.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons/dist/index.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js
- /home/c0un7z3r0/DEV/portfolio_new/webpack.config.prod.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/lib/webpack-cli.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/lib/bootstrap.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/bin/cli.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack/bin/webpack.js

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at makeWebpackError (/home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack/lib/Compilation.js:2841:12
    at eval (eval at create (/home/c0un7z3r0/DEV/portfolio_new/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:68:1)
-- inner error --
Error: Could not find the npm peerDependency "favicons".
Please run:
npm i favicons
 - or -
yarn add favicons

Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/sharp/lib/constructor.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/sharp/lib/index.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons/dist/helpers.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons/dist/index.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js
- /home/c0un7z3r0/DEV/portfolio_new/webpack.config.prod.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/lib/webpack-cli.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/lib/bootstrap.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/bin/cli.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack/bin/webpack.js

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at loadFaviconsLibrary (/home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:562:11)
    at FaviconsWebpackPlugin.generateFaviconsWebapp (/home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:403:22)
    at FaviconsWebpackPlugin.generateFavicons (/home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:315:21)
    at /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:117:18
    at /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/cache.js:155:5
    at CacheFacade.providePromise (/home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack/lib/CacheFacade.js:344:24)
caused by plugins in Compilation.hooks.processAssets
Error: Could not find the npm peerDependency "favicons".
Please run:
npm i favicons
 - or -
yarn add favicons

Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/sharp/lib/constructor.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/sharp/lib/index.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons/dist/helpers.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons/dist/index.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js
- /home/c0un7z3r0/DEV/portfolio_new/webpack.config.prod.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/lib/webpack-cli.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/lib/bootstrap.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack-cli/bin/cli.js
- /home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack/bin/webpack.js

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at loadFaviconsLibrary (/home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:562:11)
    at FaviconsWebpackPlugin.generateFaviconsWebapp (/home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:403:22)
    at FaviconsWebpackPlugin.generateFavicons (/home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:315:21)
    at /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/index.js:117:18
    at /home/c0un7z3r0/DEV/portfolio_new/node_modules/favicons-webpack-plugin/src/cache.js:155:5
    at CacheFacade.providePromise (/home/c0un7z3r0/DEV/portfolio_new/node_modules/webpack/lib/CacheFacade.js:344:24)
```

**Comment by jantimon** [comment]
Please read the npm documentation on how you can install the favicons npm package.

If harp is not supported for your operation system please check https://www.npmjs.com/package/sharp

**Comment by ACregan** [comment]
npm favicons package is installed as a dependency in the same project. Installing sharp via npm locally and globally does not fix the issue.

**Comment by RM-Eric** [comment]
I am getting the same thing, but only when webpack runs in production mode. In development mode, it runs fine. Any ideas?

webpack: 5.64.1
webpack-cli: 4.9.1
webpack-dev-server 4.4.0
