### ISSUE TITLE
Support favicon version 7 (`npm i favicon` will install version 7+)

### ISSUE THREAD

**Issue by kevinvalk** [jantimon/favicons-webpack-plugin#302]
## Current behaviour 💣
Running a webpack build using favicons 7+ will result in
```
#27 5.123 /node_modules/favicons-webpack-plugin/src/index.js:562
#27 5.123     throw new Error(
#27 5.123           ^
#27 5.123
#27 5.123 Error: Could not find the npm peerDependency "favicons".
#27 5.123 Please run:
#27 5.123 npm i favicons
#27 5.123  - or -
#27 5.123 yarn add favicons
#27 5.123
#27 5.123 Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/favicons/dist/index.js from /node_modules/favicons-webpack-plugin/src/index.js not supported.
#27 5.123 Instead change the require of /node_modules/favicons/dist/index.js in /node_modules/favicons-webpack-plugin/src/index.js to a dynamic import() which is available in all CommonJS modules.
#27 5.123     at loadFaviconsLibrary (/node_modules/favicons-webpack-plugin/src/index.js:562:11)
#27 5.123     at FaviconsWebpackPlugin.generateFaviconsWebapp (/node_modules/favicons-webpack-plugin/src/index.js:403:22)
#27 5.123     at FaviconsWebpackPlugin.generateFavicons (/node_modules/favicons-webpack-plugin/src/index.js:315:21)
#27 5.123     at /node_modules/favicons-webpack-plugin/src/index.js:117:18
#27 5.123     at /node_modules/favicons-webpack-plugin/src/cache.js:155:5
#27 5.123     at CacheFacade.providePromise (/node_modules/webpack/lib/CacheFacade.js:337:24)
#27 5.146 error Command failed with exit code 1.
#27 5.146 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behaviour ☀️
A normal build

### Reproduction Example 👾
```
...
    "favicons": "^7.0.0-beta.3",
    "favicons-webpack-plugin": "^5.0.2",
...
```
## Environment 🖥

```
Node.js v16.14.0
darwin 21.3.0
```

```
│ ├── favicons-webpack-plugin@5.0.2 deduped
│ ├── favicons@7.0.0-beta.3 deduped
│ ├─┬ file-loader@6.2.0
│ │ └── webpack@5.69.1 deduped
│ ├── html-webpack-plugin@5.5.0 deduped
│ ├── webpack-cli@4.9.2 deduped
│ └── webpack@5.69.1 deduped
```

**Comment by jantimon** [comment]
sounds like we should switch to .mjs

**Comment by simongellis-attentive** [comment]
Lol, I literally posted the same request at the same time. Closing mine as a dupe

**Comment by synedra-mpe** [comment]
```
yarn audit v1.22.17
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Prototype Pollution in minimist                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.2.6                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ favicons                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ favicons > to-ico > resize-img > jimp > mkdirp > minimist    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1067342                     │
└───────────────┴──────────────────────────────────────────────────────────────┘

```

It woould really be nice, that we could make use of favicons 7, which does not depend on old version of minimist.

**Comment by GersonDantas** [comment]
I managed to solve my problem by adding an HTML <script> tag pointing to the favicons folder on unpkg.com. I don't know what effects this will have on other browsers, but chrome didn't have any problems.
the tag looked like this:
<script type="text/html" src="https://unpkg.com/browse/favicons/"></script>

Will this present problems?

**Comment by ximex** [comment]
now favicons v7 stable is released. pls make this lib compatible with it.
https://github.com/itgalaxy/favicons/releases/tag/v7.0.0

**Comment by alecgibson** [comment]
While this isn't compatible with v7, the [`peerDependency`](https://github.com/jantimon/favicons-webpack-plugin/blob/4a3347f0d29e0da8b386e8038c31daa89ed9d632/package.json#L75) should also probably be updated to:

```
"favicons": ">= 6.2.0 7.0.0"
```

**Comment by awdr74100** [comment]
Making the library compatible with v7 would be awesome:

```ts
{
  plugins: [
    new HtmlWebpackPlugin({
      template: resolve(__dirname, "public", "index.html"),
    }),
    new FaviconsWebpackPlugin({
      logo: resolve(__dirname, "public", "favicon.svg"),
      mode: "webapp",
      cache: true,
      prefix: "assets/",
    }),
  ],
}
```

```txt
C:\Users\a7894\Desktop\webpack-ts-demo\node_modules\favicons-webpack-plugin\src\index.js:405
    const { html: tags, images, files } = await favicons(logoSource, {
                                                ^
TypeError: favicons is not a function
    at FaviconsWebpackPlugin.generateFaviconsWebapp (C:\Users\a7894\Desktop\webpack-ts-demo\node_modules\favicons-webpack-plugin\src\index.js:405:49)
    at FaviconsWebpackPlugin.generateFavicons (C:\Users\a7894\Desktop\webpack-ts-demo\node_modules\favicons-webpack-plugin\src\index.js:315:21)
    at C:\Users\a7894\Desktop\webpack-ts-demo\node_modules\favicons-webpack-plugin\src\index.js:117:18
    at C:\Users\a7894\Desktop\webpack-ts-demo\node_modules\favicons-webpack-plugin\src\cache.js:155:5
    at CacheFacade.providePromise (C:\Users\a7894\Desktop\webpack-ts-demo\node_modules\webpack\lib\CacheFacade.js:337:24)
```

**Comment by n-rodriguez** [comment]
Btw this PR works: https://github.com/jantimon/favicons-webpack-plugin/pull/291

**Comment by n-rodriguez** [comment]
Hi there! Any news?
