### ISSUE TITLE
Unexpected token '='

### ISSUE THREAD

**Issue by alexdrans** [jantimon/favicons-webpack-plugin#32]
Hey,

Currently having an issue with `favicons-webpack-plugin` via  the `favicons` package.

Here's my error;

```
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\...\node_modules\favicons-webpack-plugin\node_modules\favicons\helpers-es5.js:18:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\...\node_modules\favicons-webpack-plugin\node_modules\favicons\es5.js:11:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\...\node_modules\favicons-webpack-plugin\lib\favicons.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at DependenciesBlock.loadPitch (...\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:193:17)
    at DependenciesBlock.doBuild (...\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:241:4)
```

However, I can't see why it's happening, as `helpers-es5.js:18` is [this line](https://github.com/haydenbleasel/favicons/blob/master/helpers-es5.js#L18)

```
var path = require('path'),
    fs = require('fs'),
    _ = require('underscore'),
    color = require('tinycolor2'),
    cheerio = require('cheerio'),
    colors = require('colors'),
    jsonxml = require('jsontoxml'),
    sizeOf = require('image-size'),
    async = require('async'),
    mkdirp = require('mkdirp'),
    Jimp = require('jimp'),
    svg2png = require('svg2png'),
    File = require('vinyl'),
    Reflect = require('harmony-reflect'),
    NRC = require('node-rest-client').Client,
    PLATFORM_OPTIONS = require('./config/platform-options.json');
```

I can't build on Windows, or Heroku, but OS X seems to build fine.

**Comment by alexdrans** [comment]
This issue was being caused by having node v4.5.0 installed. Updating to v6.5.0 fixed it!

**Comment by jantimon** [comment]
Could you please let the favicons team know?

**Comment by alexdrans** [comment]
[Already did](https://github.com/haydenbleasel/favicons/issues/152)!
