### ISSUE TITLE
Support favicons 7.x

### ISSUE THREAD

**Issue by AlecRust** [jantimon/favicons-webpack-plugin#339]
When I upgrade `favicons` 6.2.2  →  7.0.1 my webpack build fails:

```sh
$ webpack --mode production
/Users/alec/projects/my-project/node_modules/favicons-webpack-plugin/src/index.js:405
    const { html: tags, images, files } = await favicons(logoSource, {
                                                ^

TypeError: favicons is not a function
    at FaviconsWebpackPlugin.generateFaviconsWebapp (/Users/alec/projects/my-project/node_modules/favicons-webpack-plugin/src/index.js:405:49)
    at FaviconsWebpackPlugin.generateFavicons (/Users/alec/projects/my-project/node_modules/favicons-webpack-plugin/src/index.js:315:21)
    at /Users/alec/projects/my-project/node_modules/favicons-webpack-plugin/src/index.js:117:18
    at /Users/alec/projects/my-project/node_modules/favicons-webpack-plugin/src/cache.js:155:5
    at CacheFacade.providePromise (/Users/alec/projects/my-project/node_modules/webpack/lib/CacheFacade.js:337:24)

Node.js v19.0.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by andy128k** [comment]
You need to use `favicons-webpack-plugin` v6.0.0-alpha.1 with `favicons` 7.x.
