### ISSUE TITLE
Plugin does not work with Node 4.x

### ISSUE THREAD

**Issue by juhamust** [jantimon/favicons-webpack-plugin#51]
Building fails with error:
```
Module build failed: TypeError: Buffer.alloc is not a function
```

**Comment by mattdell** [comment]
Same here. Full stacktrace I'm getting...

```
ModuleBuildError: Module build failed: TypeError: Buffer.alloc is not a function
    at n (/Users/mdell/Repos/my-project/web/node_modules/to-ico/index.js:15:21)
    at /Users/mdell/Repos/my-project/web/node_modules/to-ico/index.js:90:18
    at process._tickCallback (node.js:379:9)
    at DependenciesBlock.onModuleBuildFailed (/Users/mdell/Repos/my-project/web/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/mdell/Repos/my-project/web/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/mdell/Repos/my-project/web/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/mdell/Repos/my-project/web/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /Users/mdell/Repos/my-project/web/node_modules/favicons-webpack-plugin/lib/favicons.js:32:23
    at /Users/mdell/Repos/my-project/web/node_modules/favicons-webpack-plugin/lib/favicons.js:56:21
    at /Users/mdell/Repos/my-project/web/node_modules/favicons/es5.js:193:28
    at /Users/mdell/Repos/my-project/web/node_modules/async/lib/async.js:52:16
    at /Users/mdell/Repos/my-project/web/node_modules/async/lib/async.js:696:30
    at /Users/mdell/Repos/my-project/web/node_modules/async/lib/async.js:167:37
```
